plugins:
  - jest

env:
  es2021: true
  node: true
  jest: true
  browser: true

overrides: []

extends:
  - airbnb-base
  - plugin:jest/recommended

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules: 
  no-console: 0
  import/extensions: 
  - error
  - ignorePackages
  - js: always
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  max-len: [2, 119]
  semi: [2, "always"]